---
title: "MLE Results"
author: "Heidy Shi"
date: "August 29, 2019"
output: 
  ioslides_presentation:
    widescreen: true
    fig_width: 10
    fig_height: 4
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.table.format = "html")
library(tidyverse)
library(ggrepel)
library(sn)
library(e1071)
library(knitr)
library(kableExtra)
```

##Bayes vs Boostrap CIs

```{r Bayes vs Boostrap CI Tidy Data, include = FALSE}
combined_results <- read.csv("./Results/bayes_vs_bootstrap_full_data_set.csv")
width_results <- combined_results %>% select("trial", "N.pop", "skew", starts_with("width"))

names(width_results) <- substring(names(width_results), 7)
new_col_names <- c("Trial", "N.pop", "Skew", "T Dist", "BCaExp", "Bayes SDP5", 
                   "Bayes SDP10", "Bayes SDP15", "Bayes SDP20", "Bayes SDP25",
                   "Bayes SDP30")
colnames(width_results) <- new_col_names

width_results <- width_results %>% gather("T Dist", "BCaExp", "Bayes SDP5", 
                                          "Bayes SDP10", "Bayes SDP15", "Bayes SDP20", 
                                          "Bayes SDP25", "Bayes SDP30",
                                          key = "CI.type", value = "width")


#Generate boxplot for different width CIs

means <- aggregate(width ~ CI.type + Skew, width_results, mean) #calculate means by CI.type to generate labels
```
```{r Bayes vs Boostrap CI Plot, fig.width = 10, fig.height = 5}
width_results %>% group_by(CI.type) %>% arrange(desc(CI.type)) %>% 
  ggplot(aes(x = as.factor(CI.type), y = width)) +
  geom_boxplot() +
  geom_hline(yintercept = 6.2) +
  geom_hline(yintercept = 20) +
  stat_summary(fun.y = mean, colour = "darkred", 
               geom="point", shape = 18, size = 3, show.legend = FALSE)+
  geom_text_repel(data = means, aes(label = round(width, digits = 2))) +
  facet_wrap(~Skew, labeller = label_both) +
  coord_flip()
```
<div class="notes">
- N.pop = 10
- N.trials = 500
- Mu Prior = 70
</div>

##Cover Perentages

```{r}
cover_percentages <- combined_results %>% group_by(skew) %>% select("skew", starts_with("cover")) %>% 
  summarise_each(mean)
colnames(cover_percentages) <- c("skew", "Tdist", "BCaExp", "BayesSDP5",
                                 "BayesSDP10", "BayesSDP15",
                                  "BayesSD20", "BayesSDP25", "BayesSDP30")

cover_percentages %>% kable() %>% kable_styling(font_size = 20) %>% 
  column_spec(1, bold = T) %>% 
  column_spec(2, width = "15cm")
```


##MLE Mu Prior 70 Skew Normal Fit

```{r, include=FALSE}
mle_results <- read.csv("./Results/mle_bayes_muprior70_trial500.csv")
width_results <- mle_results %>% select("trial", "N.pop", "skew", starts_with("width"))

names(width_results) <- substring(names(width_results), 7)
new_col_names <- c("Trial", "N.pop", "Skew", "T Dist", "BCaExp", "Bayes SDP5", 
                   "Bayes SDP10", "Bayes SDP15", "Bayes SDP20", "Bayes SDP25",
                   "Bayes SDP30")
colnames(width_results) <- new_col_names

width_results <- width_results %>% gather("T Dist", "BCaExp", "Bayes SDP5", 
                                          "Bayes SDP10", "Bayes SDP15", "Bayes SDP20", 
                                          "Bayes SDP25", "Bayes SDP30",
                                          key = "CI.type", value = "width")

#Generate boxplot for different width CIs

means <- aggregate(width ~ CI.type + Skew, width_results, mean) #calculate means by CI.type to generate labels
```
```{r, fig.height=5}
width_results %>% group_by(CI.type) %>% arrange(desc(CI.type)) %>% 
  ggplot(aes(x = as.factor(CI.type), y = width)) +
  geom_boxplot() +
  geom_hline(yintercept = 6.2) +
  geom_hline(yintercept = 20) +
  stat_summary(fun.y = mean, colour = "darkred", 
               geom="point", shape = 18, size = 3, show.legend = FALSE)+
  geom_text_repel(data = means, aes(label = round(width, digits = 2))) +
  facet_wrap(~Skew, labeller = label_both) +
  coord_flip()
```

##Cover Percentages

```{r}
cover_percentages <- mle_results %>% group_by(skew) %>% 
  select("skew", starts_with("cover")) %>% 
  summarise_each(mean)

colnames(cover_percentages) <- c("skew", "Tdist", "BCaExp", "BayesSDP5", 
                                 "BayesSDP10", "BayesSDP15",
                                 "BayesSD20", "BayesSDP25", "BayesSDP30")
cover_percentages %>% kable() %>% kable_styling(font_size = 20) %>% 
  column_spec(1, bold = T) %>% 
  column_spec(2, width = "15cm")
```


##MLE Mu Prior 70 Fixed Gamma Skew Normal Fit

```{r, include = FALSE}
mle_results <- read.csv("./Results/mle_bayes_fixedgam_muprior70_trial100.csv")
width_results <- mle_results %>% select("trial", "N.pop", "skew", starts_with("width"))

names(width_results) <- substring(names(width_results), 7)
new_col_names <- c("Trial", "N.pop", "Skew", "T Dist", "BCaExp", "Bayes SDP5", 
                   "Bayes SDP10", "Bayes SDP15", "Bayes SDP20", "Bayes SDP25",
                   "Bayes SDP30")
colnames(width_results) <- new_col_names

width_results <- width_results %>% gather("T Dist", "BCaExp", "Bayes SDP5", 
                                          "Bayes SDP10", "Bayes SDP15", "Bayes SDP20", 
                                          "Bayes SDP25", "Bayes SDP30",
                                          key = "CI.type", value = "width")

#Generate boxplot for different width CIs

means <- aggregate(width ~ CI.type + Skew, width_results, mean) #calculate means by CI.type to generate labels
```
```{r, fig.height=5}
width_results %>% group_by(CI.type) %>% arrange(desc(CI.type)) %>% 
  ggplot(aes(x = as.factor(CI.type), y = width)) +
  geom_boxplot() +
  geom_hline(yintercept = 6.2) +
  geom_hline(yintercept = 20) +
  stat_summary(fun.y = mean, colour = "darkred", 
               geom="point", shape = 18, size = 3, show.legend = FALSE)+
  geom_text_repel(data = means, aes(label = round(width, digits = 2))) +
  facet_wrap(~Skew, labeller = label_both) +
  coord_flip()
```

##Cover Percentages

```{r}
cover_percentages <- mle_results %>% group_by(skew) %>% 
  select("skew", starts_with("cover")) %>% 
  summarise_each(mean)

colnames(cover_percentages) <- c("skew", "Tdist", "BCaExp", "BayesSDP5", 
                                 "BayesSDP10", "BayesSDP15",
                                 "BayesSD20", "BayesSDP25", "BayesSDP30")
cover_percentages %>% kable() %>% kable_styling(font_size = 20) %>% 
  column_spec(1, bold = T) %>% 
  column_spec(2, width = "15cm")
```

##MLE Mu Prior 70 Truncated Normal Fit

```{r, include = FALSE}
mle_results <- read.csv("./Results/mle_bayes_truncated_normal_muprior70_trial100.csv")
width_results <- mle_results %>% select("trial", "N.pop", "skew", starts_with("width"))

names(width_results) <- substring(names(width_results), 7)
new_col_names <- c("Trial", "N.pop", "Skew", "T Dist", "BCaExp", "Bayes SDP5", 
                   "Bayes SDP10", "Bayes SDP15", "Bayes SDP20", "Bayes SDP25",
                   "Bayes SDP30")
colnames(width_results) <- new_col_names

width_results <- width_results %>% gather("T Dist", "BCaExp", "Bayes SDP5", 
                                          "Bayes SDP10", "Bayes SDP15", "Bayes SDP20", 
                                          "Bayes SDP25", "Bayes SDP30",
                                          key = "CI.type", value = "width")

#Generate boxplot for different width CIs

means <- aggregate(width ~ CI.type + Skew, width_results, mean) #calculate means by CI.type to generate labels
```
```{r, fig.height=5}
width_results %>% group_by(CI.type) %>% arrange(desc(CI.type)) %>% 
  ggplot(aes(x = as.factor(CI.type), y = width)) +
  geom_boxplot() +
  geom_hline(yintercept = 6.2) +
  geom_hline(yintercept = 20) +
  stat_summary(fun.y = mean, colour = "darkred", 
               geom="point", shape = 18, size = 3, show.legend = FALSE)+
  geom_text_repel(data = means, aes(label = round(width, digits = 2))) +
  facet_wrap(~Skew, labeller = label_both) +
  coord_flip()
```

##Cover Percentages

```{r}
cover_percentages <- mle_results %>% group_by(skew) %>% 
  select("skew", starts_with("cover")) %>% 
  summarise_each(mean)

colnames(cover_percentages) <- c("skew", "Tdist", "BCaExp", "BayesSDP5", 
                                 "BayesSDP10", "BayesSDP15",
                                 "BayesSD20", "BayesSDP25", "BayesSDP30")
cover_percentages %>% kable() %>% kable_styling(font_size = 20) %>% 
  column_spec(1, bold = T) %>% 
  column_spec(2, width = "15cm")
```

##Mixture Distributions with MLE fitted to a Truncated Normal Distribution
```{r}
mixture <- read.csv("./Results/mle_mixture_trial100_muprior80and50_tnorm.csv")

mixture %>% group_by(mean1, mean2) %>% 
  summarize(
    avgcorrect = mean(perc.correct)
  ) %>% 
  kable() %>% 
  kable_styling(bootstrap_options = "striped", full_width = F) %>% 
  footnote(general = "N.pop = 25, N.trials = 100")
```



##MLE Mu Prior 50, Skewnormal Fit

```{r, include = FALSE}
mle_results <- read.csv("./Results/mle_bayes_muprior50.csv")
width_results <- mle_results %>% select("trial", "N.pop", "skew", starts_with("width"))

names(width_results) <- substring(names(width_results), 7)
new_col_names <- c("Trial", "N.pop", "Skew", "T Dist", "BCaExp", "Bayes SDP5", 
                   "Bayes SDP10", "Bayes SDP15", "Bayes SDP20", "Bayes SDP25",
                   "Bayes SDP30")
colnames(width_results) <- new_col_names

width_results <- width_results %>% gather("T Dist", "BCaExp", "Bayes SDP5", 
                                          "Bayes SDP10", "Bayes SDP15", "Bayes SDP20", 
                                          "Bayes SDP25", "Bayes SDP30",
                                          key = "CI.type", value = "width")

#Generate boxplot for different width CIs

means <- aggregate(width ~ CI.type + Skew, width_results, mean) #calculate means by CI.type to generate labels
```
```{r, fig.height=5}
width_results %>% group_by(CI.type) %>% arrange(desc(CI.type)) %>% 
  ggplot(aes(x = as.factor(CI.type), y = width)) +
  geom_boxplot() +
  geom_hline(yintercept = 6.2) +
  geom_hline(yintercept = 20) +
  stat_summary(fun.y = mean, colour = "darkred", 
               geom="point", shape = 18, size = 3, show.legend = FALSE)+
  geom_text_repel(data = means, aes(label = round(width, digits = 2))) +
  facet_wrap(~Skew, labeller = label_both) +
  coord_flip()
```

##Cover Percentages

```{r}
cover_percentages <- mle_results %>% group_by(skew) %>% 
  select("skew", starts_with("cover")) %>% 
  summarise_each(mean)

colnames(cover_percentages) <- c("skew", "Tdist", "BCaExp", "BayesSDP5", 
                                 "BayesSDP10", "BayesSDP15",
                                 "BayesSD20", "BayesSDP25", "BayesSDP30")
cover_percentages %>% kable() %>% kable_styling(font_size = 20) %>% 
  column_spec(1, bold = T) %>% 
  column_spec(2, width = "15cm")
```


